config/routes.rb
NewTowerFm::Application.routes.draw do

  get "welcome/index"
  devise_for :users

  resources :broadcasts
  resources :people, :people, param: :slug

  root 'welcome#index'

end

app/models/broadcast.rb
class Broadcast < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates_presence_of :slug

  def to_param
    slug
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end
end

app/controllers/broadcasts_controller.rb
class BroadcastsController < ApplicationController
  def new
  end

  def create
    @broadcast = Broadcast.new(broadcast_params)

    @broadcast.save
    redirect_to @broadcast
  end

  def show
    @broadcast = Broadcast.find(params[:id])
  end

  def index
    @broadcasts = Broadcast.all
  end

  private
    def broadcast_params
      params.require(:broadcast).permit(:broadcast_name, :description)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find_by(slug: params[:slug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params[:person].permit(:first_name, :last_name, :slug, :email, :twitter, :bio, :website, :staff, :visible, :admin)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(people)
    gravatar_id = Digest::MD5.hexdigest(people.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
  end

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/broadcasts_helper.rb
module BroadcastsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/broadcasts/index.html.erb
<h1>Listing broadcasts</h1>

<table>
  <tr>
    <th>Broadcast Name</th>
    <th>Description</th>
  </tr>

  <% @broadcasts.each do |broadcast| %>
    <tr>
      <td><%= broadcast.broadcast_name %></td>
      <td><%= broadcast.description %></td>
    </tr>
  <% end %>
</table>

app/views/broadcasts/new.html.erb
<h1>New Broadcast</h1>

<%= form_for :broadcast, url: broadcasts_path do |f| %>
  <p>
    <%= f.label :broadcast_name %><br>
    <%= f.text_field :broadcast_name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/broadcasts/show.html.erb
<h2><%= @broadcast.broadcast_name %></h2>

<p><%= @broadcast.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewTowerFm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="user_nav">
  <% if user_signed_in? %>
    <nav class="admin__menu">
      <ul>
        <li>Logged in as <strong><%= current_user.email %></strong>.</li>
        <li><%= link_to "New Broadcast", new_broadcast_path %></li>
        <li><%= link_to "New Person", new_person_path %></li>
        <li><%= link_to 'My Account', edit_user_registration_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

      <% else %>
        <li><%= link_to "To the Batcave!", new_user_session_path %></li>
      <% end %>
      </ul>
    </nav>


</div>

<header class="site__header" role="banner">
  <h1><%= link_to "Tower.fm", root_url %></h1>

  <nav class="site__nav" role="navigation">
    <ul>
      <li><%= link_to "Broadcasts", broadcasts_path %></li>
      <li><%= link_to "People", people_path %></li>
    </ul>
  </nav>
</header>



<div class="alerts">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>


<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

  <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <div class="field">
    <%= f.label :twitter %>
    <%= f.text_field :twitter %>
  </div>

  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="field">
    <%= f.check_box :visible %>
    <%= f.label :visible %>
  </div>

  <div class="field">
    <%= f.check_box :staff %>
    <%= f.label :staff %>
  </div>

  <div class="field">
    <%= f.check_box :admin %>
    <%= f.label :admin %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= image_tag avatar_url(@person) %>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= image_tag avatar_url(person) %></td>
        <td>
          <%= link_to(person) do %>
            <%= person.first_name %> <%= person.last_name %>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<figure class="alignleft">
  <%= image_tag avatar_url(@person) %>
</figure>

<h2><%= @person.first_name %> <%= @person.last_name %> <% if @person.staff? %><small>Staff</small><% end %></h2>

<%= markdown @person.bio %>

<%= link_to (@person.website) do %>
  <%= @person.first_name %>'s Website
<% end %>

<a href="https://twitter.com/<%= @person.twitter %>" class="twitter-follow-button" data-show-count="true" data-lang="en">Follow <%= @person.twitter %></a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>